avalang-global/AutomationX

docs/endpoints/global-connections/delete.mdx
docs/endpoints/global-connections/list.mdx
docs/endpoints/global-connections/schema.mdx
docs/endpoints/global-connections/update.mdx
docs/endpoints/global-connections/upsert.mdx
docs/mint.json
docs/openapi.json
packages/engine/.test.env
packages/engine/jest.config.ts
packages/engine/src/lib/handler/router-executor.ts
packages/engine/test/handler/router-branching.test.ts
packages/pieces/community/respaid/package.json
packages/pieces/community/respaid/src/lib/actions/create_new_campaign.ts
packages/server/api/src/app/app.ts
packages/server/worker/package.json
packages/shared/package.json
packages/shared/src/lib/flow-run/execution/step-output.ts

- Sync from upstream 692b033185
- Ensured no `ee` code crept in

Sync upstream 692b033185

---

packages/pieces/community/firecrawl/.eslintrc.json
packages/pieces/community/firecrawl/README.md
packages/pieces/community/firecrawl/package.json
packages/pieces/community/firecrawl/project.json
packages/pieces/community/firecrawl/src/index.ts
packages/pieces/community/firecrawl/src/lib/actions/extract-with-prompt.ts
packages/pieces/community/firecrawl/src/lib/actions/extract-with-schema.ts
packages/pieces/community/firecrawl/tsconfig.json
packages/pieces/community/firecrawl/tsconfig.lib.json
packages/pieces/community/jira-cloud/package.json
packages/pieces/community/jira-cloud/src/index.ts
packages/pieces/community/jira-cloud/src/lib/actions/add-watcher-to-issue.ts
packages/pieces/community/jira-cloud/src/lib/actions/create-issue.ts
packages/pieces/community/jira-cloud/src/lib/actions/find-user.ts
packages/pieces/community/jira-cloud/src/lib/actions/link-issues.ts
packages/pieces/community/jira-cloud/src/lib/actions/update-issue.ts
packages/pieces/community/jira-cloud/src/lib/common/index.ts
packages/pieces/community/jira-cloud/src/lib/common/props.ts
packages/pieces/community/jira-cloud/src/lib/common/types.ts
tsconfig.base.json

- Sync from upstream 2aba889854
- Build runs across important projects and affected pieces

Sync upstream 2aba889854

---

.all-contributorsrc
packages/pieces/community/devin/.eslintrc.json
packages/pieces/community/devin/README.md
packages/pieces/community/devin/package.json
packages/pieces/community/devin/project.json
packages/pieces/community/devin/src/index.ts
packages/pieces/community/devin/src/lib/actions/create-session.ts
packages/pieces/community/devin/src/lib/actions/get-session-details.ts
packages/pieces/community/devin/src/lib/actions/send-message.ts
packages/pieces/community/devin/tsconfig.json
packages/pieces/community/devin/tsconfig.lib.json
packages/pieces/community/jira-cloud/package.json
packages/pieces/community/jira-cloud/src/auth.ts
tsconfig.base.json

- Sync from upstream 13ea61b030
- Ensure no `ee` code is present
- Ensure build works across core projects and affected pieces

Sync upstream 13ea61b030

---

packages/react-ui/vite.config.ts

- Refer https://github.com/avalantglobal/AutomationX/pull/16 for more context (check notes)

Disable typescript build check on FE vite build

---

packages/server/api/src/app/database/migration/common/1741578250432-switch-to-router.ts
packages/server/api/src/app/database/postgres-connection.ts
packages/server/api/src/app/database/sqlite-connection.ts

- Add a common migration to convert flows having old step type BRANCH to new step type ROUTER

[PROMP-115] Migrate BRANCH steps to ROUTER steps in the new fork

---

packages/react-ui/src/components/show-powered-by.tsx
packages/server/api/src/app/flags/flag.service.ts

[defect] fixed wrong url of  form

---

packages/server/api/src/app/file/step-file/step-file.service.ts
packages/server/api/src/app/flags/flag.service.ts
packages/server/api/src/app/helper/domain-helper.ts
packages/server/api/src/app/user-invitations/user-invitation.service.ts
packages/server/api/src/app/workers/machine/machine-controller.ts

- Introduce our own domain helper utility to construct various URLs needed across projects / services

Introduce URL constructor utility and update references across project

---

packages/server/api/src/app/flags/flag.service.ts

[defect] fixed wrong ThirdPartyRedirectUrl

---

packages/react-ui/index.html

fix: onmessage from promptx

---

packages/react-ui/src/features/flows/components/select-flow-template-dialog.tsx
packages/react-ui/src/features/flows/components/template-tabs.tsx
packages/react-ui/src/features/templates/lib/templates-api.ts
packages/shared/src/lib/flows/dto/flow-template-request.ts

- Add Tabs for my template and community in Use a Template
- Fetch API for community template

[PROMP-136] Create Support for community templates on UI

---

packages/react-ui/src/app/components/request-trial.tsx

- Update the sales contact link from UI button
- Removed flags query param as it's not beneficial to us

Update sales contact link from UI

---

packages/react-ui/src/app/routes/platform/setup/pieces/index.tsx
packages/react-ui/src/app/routes/settings/pieces/index.tsx

- update request pieces text to better align with our offering

Update request pieces text to better align with our needs

---

packages/server/api/src/app/app.ts
packages/server/api/src/app/authentication/authentication.service.ts

- Optimize authentication log in changes that were done previously (delta between this change and upstream can be found here [oof.patch](https://github.com/user-attachments/files/19359006/oof.patch))
- Update open api spec to refer our servers

Miscellaneous Fixes

---

packages/server/api/src/app/authentication/authentication.service.ts

- Community login only uses predefined platform ID, fixed that to mimic old way

fix(login): fix local platform lookup for sign-in requests

---

packages/react-ui/src/features/authentication/components/auth-form-template.tsx
packages/server/api/src/app/authentication/user-identity/user-identity-service.ts
packages/server/api/src/app/user/user-controller.ts
packages/shared/src/lib/user/user.ts

feat: login by token

---

packages/pieces/community/knowledge-base/package.json
packages/pieces/community/knowledge-base/src/index.ts
packages/pieces/community/knowledge-base/src/lib/actions/search-knowledge-base.ts
packages/server/api/src/app/database/migration/postgres/1742454177000-initial-ms-project-config.ts
packages/server/api/src/app/database/migration/sqlite/1742454177000-initial-ms-project-config.ts
packages/server/api/src/app/database/postgres-connection.ts
packages/server/api/src/app/database/sqlite-connection.ts

fix: knowledge-base-0.0.2

---

packages/react-ui/src/features/flows/lib/use-flows-bulk-actions.tsx

- add setOpenDialog flag to false to make sure dropdown menu closed

[PROMP-144] - Fix UI lags after a few click for flows deletion dropdown

---

packages/react-ui/src/app/components/dashboard-container.tsx
packages/react-ui/src/app/router/index.tsx
packages/react-ui/src/app/routes/todos/todo-details.tsx
packages/server/api/src/app/app.ts
packages/server/api/src/app/database/database-connection.ts
packages/server/api/src/app/database/migration/postgres/1742874382959-add-todos-squashed.ts
packages/server/api/src/app/database/migration/sqlite/1742874467240-add-todos-squashed.ts
packages/server/api/src/app/database/postgres-connection.ts
packages/server/api/src/app/database/sqlite-connection.ts

- Upstream released a new beta feature called todos which is partially available on community edition
- Squashed relevant migrations and added to postgres and sqlite accordingly 
- Registered the routers and controllers
- Comment section is hidden as it's an EE feature

Enable todos feature

---

packages/react-ui/src/app/routes/flows/index.tsx

- Fix bulk delete issue which happens if user checked row data is alredy deleted and including in to delete list

[PROMP-145] Fix bulk deletion issue if include already deleted in list

---

packages/react-ui/src/app/components/sidebar.tsx
packages/react-ui/src/components/ui/input.tsx

… while selecting file
- Put sidebar header logo from center to left side
- prevents the form from auto-submitting when a file is selected. Instead, submission occurs only when the user clicks the "Submit" button

[PROMP-148] Prevent Auto-Submission on File Selection and Ensure Submission Only on Button Click in Human Input Web Form

---

packages/pieces/community/groq/package.json
packages/pieces/community/groq/src/lib/actions/ask-groq.ts
packages/pieces/community/wedof/package.json
packages/pieces/community/wedof/src/index.ts
packages/pieces/community/wedof/src/lib/actions/certification-folders/update-certification-folder.ts
packages/pieces/community/wedof/src/lib/actions/me.ts
packages/pieces/community/wedof/src/lib/actions/my-organism.ts

Sync upstream 2b44fd4584

---

packages/react-ui/index.html
packages/server/api/src/app/flows/folder/folder.module.ts
packages/server/api/src/app/flows/folder/folder.service.ts

… Plus Jakatar font
- Apply Plus Jarkarta Sans googleapi font
- Show error message for folder creationg when we created duplicate folder name

[PROMP-161] Automation  > Flow >Create new folders(Name used)

---

packages/react-ui/index.html

fix: clear seesion when logout

---

docs/ai/mcp.mdx
docs/mint.json
packages/pieces/community/wedof/package.json
packages/pieces/community/wedof/src/lib/common/wedof.ts
packages/react-ui/src/app/builder/step-settings/piece-settings/connection-select.tsx
packages/server/api/src/app/helper/system-jobs/redis-system-job.ts
packages/server/api/src/app/workers/machine/machine-controller.ts
packages/server/api/src/app/workers/machine/machine-service.ts
packages/shared/src/lib/workers/index.ts

- Sync from upstream 832f8dc7a8

Sync upstream 832f8dc7a8

---

packages/react-ui/src/features/authentication/components/auth-form-template.tsx
packages/react-ui/src/lib/user-api.ts
packages/server/api/src/app/authentication/authentication.controller.ts
packages/server/api/src/app/user/user-controller.ts
packages/shared/src/lib/authentication/dto/sign-in-request.ts
packages/shared/src/lib/user/user.ts

What does this PR do?
-Support home pmtx

feat: home_pmtx

---

docker-compose.yml
docs/install/configuration/environment-variables.mdx
package-lock.json
package.json
packages/react-ui/src/app/components/sidebar.tsx
packages/react-ui/src/app/components/usage-limits-button.tsx
packages/react-ui/src/features/tables/components/fields-mapping.tsx
packages/react-ui/src/features/tables/components/import-csv-dialog.tsx
packages/react-ui/src/features/tables/lib/records-api.ts
packages/react-ui/src/features/tables/lib/store/ap-tables-client-state.tsx
packages/react-ui/src/features/tables/lib/utils.tsx
packages/server/api/src/app/tables/record/record.controller.ts
packages/server/api/src/app/tables/record/record.service.ts
packages/server/worker/package.json
packages/shared/package.json
packages/shared/src/lib/tables/dto/records.dto.ts

- Sync from upstream 4636d195c7

Sync upstream 4636d195c7

---

packages/react-ui/src/components/ui/button.tsx
packages/server/api/src/app/flags/theme.ts

- update button style to rounded
- theme color update
Fixes # (issue)

fix: promp-166 update button style and theme primary color

---

packages/pieces/community/knowledge-base/package.json
packages/pieces/community/knowledge-base/src/lib/actions/search-knowledge-base.ts

What does this PR do?
-fix: knowledge-base-0.0.3

Knowledge base

---

README.md
tools/piece-to-markdown.js

- New script `piece-to-markdown` to do what the name says
- Use this document to index BotX documents for RAG pipeline

feat: Piece to markdown utility script

---

packages/server/api/src/app/changelog/changelog.service.ts

- Disable feature preview from activepieces because we have our own

fix: disable feature preview from activepieces

---

.all-contributorsrc
docker-compose.yml
package-lock.json
package.json
packages/react-ui/src/app/mcp/mcp-piece.tsx
packages/react-ui/src/app/mcp/mcp-tools-section.tsx
packages/react-ui/src/app/routes/mcp/index.tsx
packages/react-ui/src/app/routes/mcp/mcp-client-tabs.tsx
packages/react-ui/src/app/routes/platform/security/project-role/project-role-dialog.tsx
packages/server/api/src/app/mcp/mcp-piece-controller.ts
packages/server/api/src/app/mcp/mcp-server-controller.ts
packages/server/worker/src/lib/engine/threads/worker.ts

- Sync from upstream 3c10fb1500

Sync upstream 3c10fb1500

---

packages/react-ui/src/app/components/sidebar.tsx

fix: hide user

---

packages/server/api/src/app/analytics/analytics-controller.ts
packages/server/api/src/app/analytics/analytics-service.ts
packages/shared/src/lib/analytics/index.ts

query with multiple project IDs (retrieve from  platformId)

fix: flow analytics query

---

packages/server/api/src/app/analytics/analytics-service.ts

fix query by
addSelect
andWhere

fix: fix query syntax

---

packages/pieces/community/facebook-messenger/src/lib/auth/facebook-auth.ts

use HttpRequest instead of node-fetch

fix: use HttpRequest instead of node-fetch

---

packages/pieces/community/facebook-messenger/package-lock.json
packages/pieces/community/facebook-messenger/package.json

fix: bump version for fb messenger piece

---

packages/react-ui/src/app/connections/create-edit-connection-dialog.tsx

replace connection redirect url to promptx redirect url

---

package-lock.json

chore: lock package version

---

packages/pieces/community/microsoft-outlook-email/package.json
packages/pieces/community/microsoft-outlook-email/src/lib/triggers/new-email.ts

1. Change the newEmial filter with using date getTime
Fixes # (issue)

fix: fix outlook mail Trigger issue

---

.all-contributorsrc
packages/pieces/community/forms/package.json
packages/pieces/community/forms/src/lib/actions/return-response.ts
packages/pieces/community/motion/.eslintrc.json
packages/pieces/community/motion/README.md
packages/pieces/community/motion/package.json
packages/pieces/community/motion/project.json
packages/pieces/community/motion/src/index.ts
packages/pieces/community/motion/src/lib/actions/create-project.ts
packages/pieces/community/motion/src/lib/actions/create-task.ts
packages/pieces/community/motion/src/lib/actions/find-task.ts
packages/pieces/community/motion/src/lib/actions/get-task.ts
packages/pieces/community/motion/src/lib/actions/move-task.ts
packages/pieces/community/motion/src/lib/actions/update-task.ts
packages/pieces/community/motion/src/lib/common/props.ts
packages/pieces/community/motion/src/lib/triggers/task-created.ts
packages/pieces/community/motion/tsconfig.json
packages/pieces/community/motion/tsconfig.lib.json
tsconfig.base.json

- Sync from upstream 49fb537078

Sync upstream 49fb537078

---

packages/pieces/community/facebook-messenger/package.json
packages/pieces/community/facebook-messenger/src/index.ts
packages/pieces/community/facebook-messenger/src/lib/triggers/new-message.ts

- Renamed fb piece messenger
- Fixed imports causing build issue

fix: build issue with facebook messenger piece

---

package-lock.json
packages/pieces/community/facebook-messenger/package.json
packages/pieces/community/microsoft-outlook-email/package.json

chore: bump custom piece versions and re-publish

---

docker-compose.yml
package-lock.json
package.json
packages/pieces/community/docusign/package.json
packages/pieces/community/docusign/src/index.ts
packages/pieces/community/pipedrive/package.json
packages/pieces/community/pipedrive/src/lib/actions/add-follower.ts
packages/pieces/community/pipedrive/src/lib/common/index.ts
packages/pieces/community/pipedrive/src/lib/common/props.ts
packages/pieces/community/pipedrive/src/lib/trigger/new-lead.ts
packages/pieces/community/pipedrive/src/lib/trigger/new-note.ts
packages/pieces/community/pipedrive/src/lib/trigger/new-organization.ts
packages/pieces/community/pipedrive/src/lib/trigger/updated-organization.ts
packages/pieces/community/tarvent/package.json
packages/pieces/community/tarvent/src/index.ts
packages/react-ui/src/components/ui/data-table/index.tsx
packages/react-ui/src/features/tables/components/import-csv-dialog.tsx
packages/server/api/src/app/database/migration/postgres/1749128866314-AddMcpToolFlowCascadeDelete.ts
packages/server/api/src/app/database/migration/sqlite/1749129178686-AddMcpToolFlowCascadeDeleteSqlite.ts
packages/server/api/src/app/database/postgres-connection.ts
packages/server/api/src/app/database/sqlite-connection.ts
packages/server/api/src/app/mcp/tool/mcp-tool.entity.ts

- Sync from upstream 636630ef58
Notes
- Notable change include cascade deleting the MCP flows, once their parent flows are deleted

chore: sync upstream 636630ef58

---

packages/react-ui/src/app/components/dashboard-container.tsx
packages/server/api/src/app/authentication/authentication.controller.ts
packages/server/api/src/app/database/migration/postgres/1749183083485-DefaultMCPServer.ts
packages/server/api/src/app/database/postgres-connection.ts

- Enable MCP sidebar link for navigation
- Add onboarding step to sign ups to automatically create a default MCP server (under right conditions)

feat: add onboarding step to auto create a default mcp server

---

packages/server/api/src/app/flows/flow/flow.controller.ts

fix: check quota on publish flow action

---

packages/react-ui/src/app/builder/builder-header/builder-header.tsx

fix: remove user avatar from flow builder page

---

package-lock.json
packages/pieces/community/amazon-s3/package.json
packages/pieces/community/amazon-s3/src/index.ts
packages/pieces/community/amazon-s3/src/lib/actions/generate-signed-url.ts
packages/pieces/community/docusign/package.json
packages/pieces/community/docusign/src/lib/actions/get-document.ts
packages/pieces/community/returning-ai/package.json
packages/pieces/community/returning-ai/src/index.ts
packages/pieces/community/returning-ai/src/lib/actions/react-message.ts
packages/pieces/community/returning-ai/src/lib/actions/reply-message.ts
packages/pieces/community/returning-ai/src/lib/actions/send-message.ts
packages/react-ui/src/styles.css
tools/scripts/validate-publishable-packages.ts

chore: sync upstream 543b4283ac

---

packages/pieces/community/microsoft-outlook-email/package.json
packages/pieces/community/microsoft-outlook-email/src/index.ts
packages/pieces/community/microsoft-outlook-email/src/lib/actions/download-attachment.ts

add action for ms-outlook piece
feature : download email-attachment

feat(ms-outlook): add downloadAttachment action

---

packages/shared/src/lib/support-url.ts

fix: change support url to point to promptx

---

packages/react-ui/src/features/authentication/components/auth-form-template.tsx

fix: change order of token checks on UI to let token persist first

---

packages/react-ui/src/features/authentication/components/auth-bootstrap.tsx

- This reverts commit a719f1f050f1db6756d6a30ac6384c824c4d121e.

chore: revert token ready state check to auth bootstrap

---

packages/server/api/src/assets/emails/promptx/invitation-email.html

- As the name implies
Notes
- The promptx logo doesn't render well on dark backgrounds (mobile)
- Tested against gmail and outlook desktop versions as shown below

fix(email): add social icons and links, update logo

---

packages/pieces/community/kimi-k2/README.md
packages/pieces/community/kimi-k2/package.json
packages/pieces/community/kimi-k2/project.json
packages/pieces/community/kimi-k2/src/index.ts
packages/pieces/community/kimi-k2/src/lib/actions/chat-completion.ts
packages/pieces/community/kimi-k2/src/lib/common/common.ts
packages/pieces/community/kimi-k2/tsconfig.json
packages/pieces/community/kimi-k2/tsconfig.lib.json
tsconfig.base.json

-Just add kimi node 
It almost same as OpenAi.
-Already Test.

feat(kimi): add kimi node (same as OpenAI)

---

packages/pieces/community/knowledge-base/package.json
packages/pieces/community/knowledge-base/src/index.ts
packages/pieces/community/knowledge-base/src/lib/actions/add-to-knowledge-base.ts
packages/pieces/community/knowledge-base/src/lib/actions/search-knowledge-base.ts

feat: add to knowledge base

---

packages/pieces/community/knowledge-base/package.json
packages/pieces/community/knowledge-base/src/lib/actions/search-knowledge-base.ts

fix: seach knowledge base by tag
