packages/server/api/src/app/pieces/piece-sync-service.ts, packages/server/shared/src/lib/pieces/file-pieces-utils.ts, packages/shared/src/lib/pieces/index.ts
- Introduce a new `LOCAL` syncing mode that simply scans for all pieces in the package and registers it
=> [PROMP-99] Allow for local syncing of all pieces

packages/react-ui/src/features/authentication/components/auth-form-template.tsx, packages/server/api/src/app/authentication/user-identity/user-identity-service.ts, packages/server/api/src/app/user/user-controller.ts, packages/server/api/src/app/user/user-service.ts, packages/shared/src/lib/user/user.ts
- Make `identityId` mandatory in `UserMetaInformationWithProject` as it's needed in our core login flows (optional in `UserMetaInformation` to align with other composite types)
- Remove extra db call in `/me` endpoint by getting `identityId` in 1 call
- Lint the frontend code
=> Include IdentityId with user meta information to let UI login with token

packages/server/api/src/app/flow-templates/community-flow-template.module.ts
- generate console log to track for flow-templates/community 404 issue
=> fix: promp-143 add console log to track community template 404

packages/server/api/src/app/flow-templates/community-flow-template.module.ts
- use cloud.activepieces URL directly in controller for community templates
=> [PROMP-143] use activepieces community template api directly in community controller

packages/react-ui/src/features/flows/components/select-flow-template-dialog.tsx, packages/react-ui/src/features/templates/lib/templates-api.ts, packages/server/api/src/app/app.ts, packages/server/api/src/app/flow-templates/cloud-flow-template.module.ts
- Exposed a new endpoint `/v1/flow-templates/cloud/` that gets global flow templates
- Templates are picked from `cloud` platform, i.e. ours (which means we need to create one and add to env)
- FE will call both community and cloud templates endpoint and show the result of both
=> [PROMP-140] Cloud flow templates API 

packages/react-ui/src/components/custom/FloatingChatButton.tsx, packages/react-ui/src/components/ui/user-avatar.tsx, packages/react-ui/src/features/authentication/components/auth-form-template.tsx, packages/react-ui/src/lib/authentication-session.ts
- Allow direct login through `t` query string parameter
- Allow redirects using `from` query string parameter
- Maintain existing log in scenarios too
- Misc. Update references to `getCurrentUser` to use hooks instead
Example `localhost:4200/sign-in?from=%2Fflows%2FxvN54uWsxgOctMa8kKrFA&token=<unescaped-jwt-token>`
=> fix: Allow logins and redirects using token and from query string parameters

packages/server/api/src/app/analytics/analytics-controller.ts, packages/server/api/src/app/analytics/analytics-module.ts, packages/server/api/src/app/analytics/analytics-service.ts, packages/shared/src/lib/analytics/index.ts
```
GET /api/v1/analytics/flow-performance?startDate=&endDate=
[
{
"date": "10-04-2025",
"successfulFlowRuns": 80,
"failedFlowRuns": 20,
"successfulFlowRunsDuration": 300,
"failedFlowRunsDuration": 100
},
{
"date": "11-04-2025",
"successfulFlowRuns": 80,
"failedFlowRuns": 20,
"successfulFlowRunsDuration": 300, // in milliseconds
"failedFlowRunsDuration": 100 // in milliseconds
},
{
"date": "12-04-2025",
"successfulFlowRuns": 80,
"failedFlowRuns": 20,
"successfulFlowRunsDuration": 300, // in milliseconds
"failedFlowRunsDuration": 100 // in milliseconds
}
]
GET /api/v1/analytics/overview
{
"workflowCount": 100,
"activeWorkflowCount": 2,
"flowRunCount": 400
}
```
=> feat(analytics): create 2 APIs for analytics flow-performance and overview

packages/react-ui/src/app/components/ap-dashboard-sidebar-header.tsx
- Just keep sidebar header only website name and remove logo in automation X
Fixes # (issue)
=> fix: update sidebar header with only website name

packages/server/api/src/app/analytics/analytics-controller.ts, packages/server/api/src/app/analytics/analytics-service.ts, packages/shared/src/lib/analytics/index.ts
Add 'projectId' to the filter to ensure only the flows
created by current user.
Previously, the query returned all flows.
=> fix: update analytics endpoints to calculate per project

packages/react-ui/src/app/components/platform-admin-container.tsx, packages/react-ui/src/app/components/sidebar.tsx, packages/react-ui/src/hooks/platform-hooks.ts, packages/react-ui/src/lib/platforms-api.ts, packages/server/api/src/app/platform/platform.controller.ts
- Add `is-cloud-platform` API to support checking the same from UI (without exposing the ID)
- Update UI to
- Show the toggle button for admin dashboard (this will be eventually removed)
- Show Infrastructure group in the admin dashboard if cloud platform (this will stay and the reason for this change)
- Wrapped the FE API in a react-suspense query for benefits
=> fix: display platform admin toggle if cloud platform

packages/react-ui/src/features/authentication/components/auth-form-template.tsx
- Use token from Search params first and if no token from search, will use existing local storage token.
Fixes # (issue)
=> fix: use token from search param first and use old token

packages/react-ui/src/app/routes/settings/appearance/index.tsx
- Hide Language Switcher button in settings/appereance
=> fix: hide language switcher in settings appereance

packages/react-ui/src/app/components/dashboard-container.tsx, packages/react-ui/src/app/components/settings-dropdown-menu.tsx, packages/react-ui/src/app/routes/settings/appearance/index.tsx
- Added back the language switcher to appearance page (as we removed the entire page from dropdown)
- Removed theme toggle and appearance sections from the project settings dropdown
- Removed MCP link from the sidebar as well
=> fix: remove appearance, theme toggle from project settings dropdown and remove mcp link from sidebar

packages/react-ui/src/features/tables/components/new-field-popup.tsx
- add max height to 450 for adding option items
=> fix: add max width for add field item

packages/react-ui/src/features/connections/lib/oauth-apps-hooks.ts, packages/server/api/src/app/app-connection/app-connection-service/oauth2/services/global-oauth2-service.ts
- Fix an issue where global oauth connections intermittently reverted to platform types causing refresh token issue
- Optimize piece to clientId map generation on UI
=> fix: ensure consistent types for global oauth apps to cloud oauth type

packages/server/api/src/app/user-invitations/user-invitation.service.ts
- Allow invitation request creations to return a invitation link that's active for 1 hour (this is needed for collaboration feature)
=> feat: enable invitation link

packages/server/api/src/app/app.ts, packages/server/api/src/app/database/database-connection.ts, packages/server/api/src/app/database/migration/postgres/1752736911931-project-role.ts, packages/server/api/src/app/database/migration/postgres/1752744019509-default-project-role.ts, packages/server/api/src/app/database/migration/postgres/1752746415961-add-project-role-invitation.ts, packages/server/api/src/app/database/migration/sqlite/1752743014852-project-role.ts, packages/server/api/src/app/database/migration/sqlite/1752746475364-add-project-role-invitation.ts, packages/server/api/src/app/database/postgres-connection.ts, packages/server/api/src/app/database/sqlite-connection.ts, packages/server/api/src/app/platform/platform.service.ts, packages/server/api/src/app/project-role/project-role.entity.ts, packages/server/api/src/app/project-role/project-role.module.ts, packages/server/api/src/app/project-role/project-role.service.ts, packages/server/api/src/app/user-invitations/user-invitation.entity.ts, packages/server/api/src/app/user-invitations/user-invitation.module.ts, packages/server/api/src/app/user-invitations/user-invitation.service.ts
- Add "project roles" feature that mimics the upstream ee roles but bypasses all fine grain access checks (as we don't need)
- Modified "user invitations" to now support storing projectRoleId (disabled previously due to ee limitation)
- Enabled on backend but hidden on UI (need project member feature)
Notes
- SQLite DB option doesn't seed with default roles
=> feat: project roles

packages/server/api/src/app/app.ts, packages/server/api/src/app/database/database-connection.ts, packages/server/api/src/app/database/migration/postgres/1752814412946-project-member.ts, packages/server/api/src/app/database/migration/sqlite/1752814553291-project-member.ts, packages/server/api/src/app/database/postgres-connection.ts, packages/server/api/src/app/database/sqlite-connection.ts, packages/server/api/src/app/project-member/project-member.entity.ts, packages/server/api/src/app/project-member/project-member.module.ts, packages/server/api/src/app/project-member/project-member.service.ts, packages/server/api/src/app/project-role/project-role.module.ts, packages/server/api/src/app/project/project-service.ts, packages/server/api/src/app/user-invitations/user-invitation.service.ts, packages/shared/src/index.ts, packages/shared/src/lib/project-member/index.ts
- Added "project member" entity, module, migration and integration with project service and user invitations
- Tested it to work
Notes
- This only adds a basic membership users to some projects through a single default role, no fine grained access is implemented as it's not needed
- Because of which the checkAccess() will still return true as its skipped in CE edition (ours)
=> feat: project member

packages/react-ui/index.html
- Standardize and allow token revocation message to be handled by this application iframe
Usage
- Parent (PromptX) loads app iframe using existing URL (with token)
- Parent posts token message that contains only openID and access_token (not AutomationX token)
- While logging out, parent posts revoke token message to empty local storage of all tokens
Note
- Message payload types have changed
=> fix: allow iframe message to handle token revocation

packages/pieces/community/promptx-agent/package.json
- As the title says, needed to republish to npm as previous version dependencies were faulty
=> chore: bump promptx agent version

packages/server/api/src/app/project-member/project-member.service.ts, packages/server/api/src/app/user/user-service.ts
- As the title says (missed it during feature rollout)
=> fix: enable project members in getUsersForProject to list todo assignees correctly

packages/react-ui/src/app/components/sidebar/builder/flows-navigation.tsx
- As the title says
- Will sync with upstream when it is fixed there as well
=> fix: flow builder doesn't refresh when flow is deleted from sidebar
